version: '3'
services:
  pwnboard:
    build: .
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: "nginx:latest"
    container_name: nginx
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf:ro
