version: '3'
services:
  pwnboard:
    build: .
    container_name: pwnboard
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
