uwsgi:
  # Setup the server for python3
  plugin: python3
  # Let the protocol default to wsgi unless testing
  # protocol: http
  # The filename containing the flask app
  wsgi-file: /opt/pwnboard/pwnboard.py
  # The Name of the app object in the file listed above
  callable: app
  # master: true
  # Socket Processes
  socket: :5000
  #processes: 5

  # Logging configurations
  log-5xx: true
  disable-logging: true
