---
slack:
  token_file: "/etc/pwnboard/slack_token"
  channel: "#pwnboard"
  send_updates: false
database:
  server: localhost
  port: 6379
server:
  host: localhost #http://pwnboard.local
  cache: false
  cache_time: 10
  logfile: pwnboard.log
alternate_theme: false
alert_timeout: 2
host_timeout: 5
